services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_USERS=user1,user2,user3
    volumes:
      - .:/app
    restart: unless-stopped