services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - GITLAB_TOKEN=your-token
      - PROJECT_ID=your-project-id
      - ALLOWED_USERS=user1,user2
    volumes:
      - .:/app
    restart: unless-stopped